#!/bin/bash

# This hook is called with the snake-cased name of the theme that has just been set.
# To put it into use, remove .sample from the name.
rn-presenterm-theme-hook $1
rn-zellij-theme-hook $1
